const colors = {
  light: {
    text: "#0A1628",
    tint: "#2D7BFF",
    background: "#F0F5FF",
    foreground: "#0A1628",
    card: "#FFFFFF",
    cardForeground: "#0A1628",
    primary: "#2D7BFF",
    primaryForeground: "#FFFFFF",
    secondary: "#EBF0FF",
    secondaryForeground: "#0A1628",
    muted: "#E8EEFF",
    mutedForeground: "#6B7A9A",
    accent: "#FF6B2B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D1DEFF",
    input: "#D1DEFF",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#E8F0FF",
    tint: "#4D8FFF",
    background: "#080F1E",
    foreground: "#E8F0FF",
    card: "#0F1C33",
    cardForeground: "#E8F0FF",
    primary: "#2D7BFF",
    primaryForeground: "#FFFFFF",
    secondary: "#142040",
    secondaryForeground: "#E8F0FF",
    muted: "#142040",
    mutedForeground: "#8899BB",
    accent: "#FF6B2B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3060",
    input: "#1E3060",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 14,
};

export default colors;
